### PR TITLE
Add this link in multilingual extension 

### PR DESCRIPTION
**Pull request by uzairhaider502**
Kindly add this link in multilingual extension
https://www.hindimoviestv.com/
thank you.

### CODE REVIEW

**Comment by C10udburst** [comment]
bruh

**Comment by uzairhaider502** [comment]
Sorry!

**Comment by uzairhaider502** [comment]
Are you guys gonna be added that link?

**Comment by uzairhaider502** [comment]
https://www.hindimoviestv.com/

**Comment by C10udburst** [comment]
you've opened a pr which has a merge issue you can't even fix because you aren't PRing your own code

**Pull request closed without merging**
