### PR TITLE
Upgrade gradle

### PR DESCRIPTION
**Pull request by Luna712**
I was able to get it to build properly but I can not be certain if prerelease with GitHub actions will correctly work, but building prerelease manually works for me now. Please close if you do not want this done, in which case, I appologize.

### CODE REVIEW

**Comment by Luna712** [comment]
> even if workflow fails, i think we need latest log to see whats wrong

@IndusAryan 

Indeed, unless we know what still fails, we can't really fix it, unless we use something like act to test locally, but that isn't always super reliable either. Since it worked for me to build locally unless we get latest log on why it fails, we can't know what is wrong and how to fix it.

**Comment by fire-light42** [comment]
@C10udburst how much will this fuck over prereleases?

**Comment by Luna712** [comment]
> bro/sis @Luna712 don't bump desugar lib plsl i am testing one thing!

Bumping it requires bumping gradle so I thought I would just do it all at once but okay, I will revert that.

**Comment by Luna712** [comment]
> bro/sis @Luna712 don't bump desugar lib plsl i am testing one thing!

I got rid of that part

**Comment by C10udburst** [comment]
> @C10udburst how much will this fuck over prereleases?

It will fuck it over, but I have found a way to fix it I think. Basically removing the dependency `build` from `makeJar` and running `makeJar` after `build` and `assemblePrerelease` (not concurrently). Don't worry, I'll make the changes when the PR gets merged/marked as ready to be merged.

**Review by C10udburst — APPROVED** [review]

**Comment by Luna712** [comment]
This should be okay now.

**Review by fire-light42 — APPROVED** [review]
@C10udburst Merge anytime if you feel like the build system can handle it

**Comment by Luna712** [comment]
Thanks @C10udburst

**Pull request merged**
