### PR TITLE
arabicLanguage

### PR DESCRIPTION
**Pull request by SANCTI-afk**
Full arabic

### CODE REVIEW

**Comment by ImZaw** [comment]
Ill check it when im home

**Comment by SANCTI-afk** [comment]
> Ill check it when im home

you almost forgot...wake up dn dn dn

**Comment by SANCTI-afk** [comment]
Thanks in advance bro

**Comment by ImZaw** [comment]
> > Ill check it when im home
> 
> you almost forgot...wake up dn dn dn

my bad i forgot to check it out everything is good it just that comment i gave on the code

**Comment by Blatzar** [comment]
@AbdullahM0hamed :pray:

**Pull request merged**
