### PR TITLE
Fix to define Cartoon as episode based

### PR DESCRIPTION
**Pull request by Luna712**
Supposed to be based on https://github.com/recloudstream/cloudstream/blob/282b25b665fd2fe9f7a596e3d6c9067ea540730c/app/src/main/java/com/lagradost/cloudstream3/ui/result/ResultViewModel2.kt#L643

### CODE REVIEW

**Review by fire-light42 — CHANGES_REQUESTED** [review]
Please at least think of some optimizations, you just alloc for a simple if statement. [source](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:kotlin,selection:(endColumn:1,endLineNumber:9,positionColumn:1,positionLineNumber:9,selectionStartColumn:1,selectionStartLineNumber:9,startColumn:1,startLineNumber:9),source:'//+Type+your+code+here,+or+load+an+example.%0Afun+n1(num:+Int):+Boolean+%3D+num+in+listOf(1,2,3,4,5,10)%0Afun+n2(num:+Int):+Boolean+%3D+when+(num)+%7B%0A++++1,2,3,4,5,10+-%3E+true%0A++++else+-%3E+false%0A%7D%0Afun+n3(num:+Int):+Boolean+%3D+num%3D%3D1%7C%7Cnum%3D%3D2%7C%7Cnum%3D%3D3%7C%7Cnum%3D%3D4%7C%7Cnum%3D%3D5%7C%7Cnum%3D%3D10%0A%0A'),l:'5',n:'0',o:'Kotlin+source+%231',t:'0')),k:36.63741786731504,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:kotlinc2021,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'1',verboseDemangling:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:kotlin,libs:!(),options:'',overrides:!(),selection:(endColumn:2,endLineNumber:98,positionColumn:2,positionLineNumber:98,selectionStartColumn:2,selectionStartLineNumber:98,startColumn:2,startLineNumber:98),source:1),l:'5',n:'0',o:'+kotlinc+2.0.21+(Editor+%231)',t:'0')),k:37.527183729806964,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'rustc+1.73.0',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+kotlinc+2.0.21+(Compiler+%231)',t:'0')),k:25.835398402877995,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

**Comment by Luna712** [comment]
> Please at least think of some optimizations, you just alloc for a simple if statement. [source](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:kotlin,selection:(endColumn:1,endLineNumber:9,positionColumn:1,positionLineNumber:9,selectionStartColumn:1,selectionStartLineNumber:9,startColumn:1,startLineNumber:9),source:'//+Type+your+code+here,+or+load+an+example.%0Afun+n1(num:+Int):+Boolean+%3D+num+in+listOf(1,2,3,4,5,10)%0Afun+n2(num:+Int):+Boolean+%3D+when+(num)+%7B%0A++++1,2,3,4,5,10+-%3E+true%0A++++else+-%3E+false%0A%7D%0Afun+n3(num:+Int):+Boolean+%3D+num%3D%3D1%7C%7Cnum%3D%3D2%7C%7Cnum%3D%3D3%7C%7Cnum%3D%3D4%7C%7Cnum%3D%3D5%7C%7Cnum%3D%3D10%0A%0A'),l:'5',n:'0',o:'Kotlin+source+%231',t:'0')),k:36.63741786731504,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:kotlinc2021,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'1',verboseDemangling:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:kotlin,libs:!(),options:'',overrides:!(),selection:(endColumn:2,endLineNumber:98,positionColumn:2,positionLineNumber:98,selectionStartColumn:2,selectionStartLineNumber:98,startColumn:2,startLineNumber:98),source:1),l:'5',n:'0',o:'+kotlinc+2.0.21+(Editor+%231)',t:'0')),k:37.527183729806964,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'rustc+1.73.0',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+kotlinc+2.0.21+(Compiler+%231)',t:'0')),k:25.835398402877995,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

So sorry but I have no idea what you mean?

**Comment by fire-light42** [comment]
> > Please at least think of some optimizations, you just alloc for a simple if statement. [source](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:kotlin,selection:(endColumn:1,endLineNumber:9,positionColumn:1,positionLineNumber:9,selectionStartColumn:1,selectionStartLineNumber:9,startColumn:1,startLineNumber:9),source:'//+Type+your+code+here,+or+load+an+example.%0Afun+n1(num:+Int):+Boolean+%3D+num+in+listOf(1,2,3,4,5,10)%0Afun+n2(num:+Int):+Boolean+%3D+when+(num)+%7B%0A++++1,2,3,4,5,10+-%3E+true%0A++++else+-%3E+false%0A%7D%0Afun+n3(num:+Int):+Boolean+%3D+num%3D%3D1%7C%7Cnum%3D%3D2%7C%7Cnum%3D%3D3%7C%7Cnum%3D%3D4%7C%7Cnum%3D%3D5%7C%7Cnum%3D%3D10%0A%0A'),l:'5',n:'0',o:'Kotlin+source+%231',t:'0')),k:36.63741786731504,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:kotlinc2021,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'1',verboseDemangling:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:kotlin,libs:!(),options:'',overrides:!(),selection:(endColumn:2,endLineNumber:98,positionColumn:2,positionLineNumber:98,selectionStartColumn:2,selectionStartLineNumber:98,startColumn:2,startLineNumber:98),source:1),l:'5',n:'0',o:'+kotlinc+2.0.21+(Editor+%231)',t:'0')),k:37.527183729806964,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'rustc+1.73.0',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+kotlinc+2.0.21+(Compiler+%231)',t:'0')),k:25.835398402877995,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)
> 
> So sorry but I have no idea what you mean?

You are currently allocating memory taking extra cpu time, instead of using super fast tableswitch operation (aka when). Even if cs3 does not really optimize our code, refactoring fast code to be slower is a bit of a gut punch.

**Comment by Luna712** [comment]
> > > Please at least think of some optimizations, you just alloc for a simple if statement. [source](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:kotlin,selection:(endColumn:1,endLineNumber:9,positionColumn:1,positionLineNumber:9,selectionStartColumn:1,selectionStartLineNumber:9,startColumn:1,startLineNumber:9),source:'//+Type+your+code+here,+or+load+an+example.%0Afun+n1(num:+Int):+Boolean+%3D+num+in+listOf(1,2,3,4,5,10)%0Afun+n2(num:+Int):+Boolean+%3D+when+(num)+%7B%0A++++1,2,3,4,5,10+-%3E+true%0A++++else+-%3E+false%0A%7D%0Afun+n3(num:+Int):+Boolean+%3D+num%3D%3D1%7C%7Cnum%3D%3D2%7C%7Cnum%3D%3D3%7C%7Cnum%3D%3D4%7C%7Cnum%3D%3D5%7C%7Cnum%3D%3D10%0A%0A'),l:'5',n:'0',o:'Kotlin+source+%231',t:'0')),k:36.63741786731504,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:kotlinc2021,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'1',verboseDemangling:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:kotlin,libs:!(),options:'',overrides:!(),selection:(endColumn:2,endLineNumber:98,positionColumn:2,positionLineNumber:98,selectionStartColumn:2,selectionStartLineNumber:98,startColumn:2,startLineNumber:98),source:1),l:'5',n:'0',o:'+kotlinc+2.0.21+(Editor+%231)',t:'0')),k:37.527183729806964,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'rustc+1.73.0',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+kotlinc+2.0.21+(Compiler+%231)',t:'0')),k:25.835398402877995,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)
> > 
> > 
> > So sorry but I have no idea what you mean?
> 
> You are currently allocating memory taking extra cpu time, instead of using super fast tableswitch operation (aka when). Even if cs3 does not really optimize our code, refactoring fast code to be slower is a bit of a gut punch.

Oh that makes sense I didn't even think of that my intent for the change was readability I didn't even consider the performance aspect. My bad.

**Comment by Luna712** [comment]
> Please at least think of some optimizations, you just alloc for a simple if statement. [source](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:kotlin,selection:(endColumn:1,endLineNumber:9,positionColumn:1,positionLineNumber:9,selectionStartColumn:1,selectionStartLineNumber:9,startColumn:1,startLineNumber:9),source:'//+Type+your+code+here,+or+load+an+example.%0Afun+n1(num:+Int):+Boolean+%3D+num+in+listOf(1,2,3,4,5,10)%0Afun+n2(num:+Int):+Boolean+%3D+when+(num)+%7B%0A++++1,2,3,4,5,10+-%3E+true%0A++++else+-%3E+false%0A%7D%0Afun+n3(num:+Int):+Boolean+%3D+num%3D%3D1%7C%7Cnum%3D%3D2%7C%7Cnum%3D%3D3%7C%7Cnum%3D%3D4%7C%7Cnum%3D%3D5%7C%7Cnum%3D%3D10%0A%0A'),l:'5',n:'0',o:'Kotlin+source+%231',t:'0')),k:36.63741786731504,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:kotlinc2021,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'1',verboseDemangling:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:kotlin,libs:!(),options:'',overrides:!(),selection:(endColumn:2,endLineNumber:98,positionColumn:2,positionLineNumber:98,selectionStartColumn:2,selectionStartLineNumber:98,startColumn:2,startLineNumber:98),source:1),l:'5',n:'0',o:'+kotlinc+2.0.21+(Editor+%231)',t:'0')),k:37.527183729806964,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'rustc+1.73.0',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+kotlinc+2.0.21+(Compiler+%231)',t:'0')),k:25.835398402877995,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

*If* I understood correctly I think I did what you were asking...

**Review by fire-light42 — APPROVED** [review]

**Pull request merged**
