### PR TITLE
#352 Library sorting issue fixed in LibraryFragment.kt

### PR DESCRIPTION
**Pull request by MudssirAhmed**
The library scroll issue fix
[https://github.com/recloudstream/cloudstream/issues/352](url)

### CODE REVIEW

**Comment by Blatzar** [comment]
Pretty sure that was fixed in the latest commit :pensive: 
https://github.com/recloudstream/cloudstream/commit/99887534327c86bcc653dfbc84a24917d34b0fe5#diff-c3cc58326960b720f7cc17fcd15228db38a37ac9d179f18b03dd536d596f39aeR339

**Comment by Blatzar** [comment]
Bad on our part for not closing issues properly :sob:

**Comment by MudssirAhmed** [comment]
> Pretty sure that was fixed in the latest commit :pensive: 
> https://github.com/recloudstream/cloudstream/commit/99887534327c86bcc653dfbc84a24917d34b0fe5#diff-c3cc58326960b720f7cc17fcd15228db38a37ac9d179f18b03dd536d596f39aeR339

I checked this commit but the issue is not resolved, that's why I create the PR
🙂

**Comment by Blatzar** [comment]
> issue is not resolved 

Yet I cannot replicate it anymore, please send a video on latest beta showing how to replicate it. 

https://user-images.githubusercontent.com/46196380/216495290-9a7f34b5-5837-483c-b995-658d8fc78f34.mp4

**Comment by Blatzar** [comment]
No worries I will just close this :+1: 
Please come over to \#dev in discord so the team knows what you're working on so no one does any double work :pray:

**Comment by MudssirAhmed** [comment]
Okay thanks, I'll ping in dev when I start work on any issue.

**Comment by MudssirAhmed** [comment]
I'm unable to send messages to the dev, Is there any permission issue?

**Pull request closed without merging**
