### PR TITLE
Fix cast recycler scrolling

### LINKED ISSUE #563: Caste recycler works only once
### Steps to reproduce

open app and swipe casts on movie or a series
it will swipe
now go to other movie or series it will open recommendations fragment.

### Expected behavior

caste should work everytime 

### Actual behavior

it doesn't work always,probably users needs to belong to a upper caste :) :harold:

### Cloudstream version and commit hash

Latest PreRelease

### Android version

A13

### Logcat

_No response_

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Luna712**
Fixes #563

### CODE REVIEW

**Comment by fire-light42** [comment]
This does not fix it completely, as it was still stuck after going to a recommendation, then pressing `<-`.

**Comment by Luna712** [comment]
> This does not fix it completely, as it was still stuck after going to a recommendation, then pressing `<-`.

Ah right will fix soon thanks!

**Comment by Luna712** [comment]
@fire-light42 I fixed it as best I could. I think it works mostly but sometimes if you open recommendations and close it it takes a few seconds for cast recycler to work again or if you scroll up or down sometimes. Not 100% reliable but a lot better then it was (I think anyway)

**Comment by fire-light42** [comment]
> @fire-light42 I fixed it as best I could. I think it works mostly but sometimes if you open recommendations and close it it takes a few seconds for cast recycler to work again or if you scroll up or down sometimes. Not 100% reliable but a lot better then it was (I think anyway)

If it is not 100% reliable, then you need to comment that in the code.

**Comment by Luna712** [comment]
> > @fire-light42 I fixed it as best I could. I think it works mostly but sometimes if you open recommendations and close it it takes a few seconds for cast recycler to work again or if you scroll up or down sometimes. Not 100% reliable but a lot better then it was (I think anyway)
> 
> If it is not 100% reliable, then you need to comment that in the code.

@fire-light42 

Thanks, I added a comment for that now.

**Comment by fire-light42** [comment]
It is indeed very jank, but I guess it is better than what we have at the moment. Discord storing ids instead of views 😔

**Pull request merged**
