### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by C10udburst**

### CODE REVIEW

**Comment by Blatzar** [comment]
What's going on here?

**Comment by C10udburst** [comment]
> What's going on here?

I tried to set up crowdin but it doesn't work :idk:

**Comment by andrii-bodnar** [comment]
Hi there!

I'm Andrii from Crowdin, and I noticed that you've been experiencing some difficulties with integrating your repository with Crowdin.

I'd be happy to help you out with that. What about integrating an automatic GH Workflow using [Crowdin GH Action](https://github.com/crowdin/github-action)?

I can create a pull request with all of the necessary configurations for you. Let me know if this sounds helpful! 🙂

**Comment by C10udburst** [comment]
> Hi there!
> 
> I'm Andrii from Crowdin, and I noticed that you've been experiencing some difficulties with integrating your repository with Crowdin.
> 
> I'd be happy to help you out with that. What about integrating an automatic GH Workflow using [Crowdin GH Action](https://github.com/crowdin/github-action)?
> 
> I can create a pull request with all of the necessary configurations for you. Let me know if this sounds helpful! :slightly_smiling_face:

sounds great, help would be appreciated :pray:

**Comment by C10udburst** [comment]
nevermind, I've set up weblate instead, thank you for the offer nevertheless

**Pull request closed without merging**
