### PR TITLE
chore: update material,kotlin compiler,newpipe extractor,rhino-js,guava,corektx

### PR DESCRIPTION
**Pull request by IndusAryan**

### CODE REVIEW

**Comment by Luna712** [comment]
@IndusAryan @fire-light42 this messes some layout up (or I at least assume it was this)

For example Simkl rating
| Screenshot_20240528_012045_CloudStream | 
|:--:| 
| *Before* |

| Screenshot_20240528_012034_CloudStream Beta |
|:--:| 
| *After* |

**Comment by IndusAryan** [comment]
messed up how ? design changes with time, if original style is still present, send me the xml of this , will see .

**Comment by fire-light42** [comment]
> messed up how ? design changes with time, if original style is still present, send me the xml of this , will see .

https://m3.material.io/components/sliders/overview it is simply how material 3 is

**Comment by Luna712** [comment]
> > messed up how ? design changes with time, if original style is still present, send me the xml of this , will see .
> 
> https://m3.material.io/components/sliders/overview it is simply how material 3 is

@fire-light42 

I'm aware of that but IMO it looks ugly how it is now and it should at least be tuned up a bit even if it can't be exactly how it was before.

**Pull request merged**
