### PR TITLE
Maintain library sort filter

### LINKED ISSUE #626: Remember library sort filter
### Describe your suggested feature

Ideally library should remember the sort order you select if you click on a movie or go back, or even if you close the app it should stay persistent, by saving to the local account data.

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Luna712**
~~It appears #626 was closed, however it does not appear to work properly, and still does not remember properly, so I went ahead and did this, if it is wrong, I apologize.~~

I did sorting in the background like this for performance, as if it wasnt it caused a few performance issues.

Resolves #626

### CODE REVIEW

**Comment by LagradOst** [comment]
closed the wrong issue

**Comment by LagradOst** [comment]
but this pr implemented the sorting and key wrong, and will therefore be closed

**Comment by LagradOst** [comment]
a correct fix will come tomorrow

**Comment by Luna712** [comment]
> but this pr implemented the sorting and key wrong, and will therefore be closed

I tested it and it works, but maybe I tested wrong?

**Comment by Luna712** [comment]
> a correct fix will come tomorrow

I appreciate it. Sorry I did this wrong then.

**Comment by Luna712** [comment]
@LagradOst this does properly work though, I might have tested wrong, but it does appear to work and maintain the sort from what at least I expected it to. Again, I apologize if I tested wrong.

I do understand working and how it should be done are two very different things, so understand if it should just be done a different way.

**Comment by LagradOst** [comment]
> @LagradOst this does properly work though, I might have tested wrong, but it does appear to work and maintain the sort from what at least I expected it to. Again, I apologize if I tested wrong.
> 
> I do understand working and how it should be done are two very different things, so understand if it should just be done a different way.

yes I know it works, but you implemented it wrong

**Comment by Luna712** [comment]
> > @LagradOst this does properly work though, I might have tested wrong, but it does appear to work and maintain the sort from what at least I expected it to. Again, I apologize if I tested wrong.
> > I do understand working and how it should be done are two very different things, so understand if it should just be done a different way.
> 
> yes I know it works, but you implemented it wrong

Okay, that I understand. Thanks for clarification. Sorry about that. Kotlin is still new to me, I more used to other languages. So I try and fail miserably at it sometimes.

**Comment by LagradOst** [comment]
> > > @LagradOst this does properly work though, I might have tested wrong, but it does appear to work and maintain the sort from what at least I expected it to. Again, I apologize if I tested wrong.
> > > I do understand working and how it should be done are two very different things, so understand if it should just be done a different way.
> > 
> > yes I know it works, but you implemented it wrong
> 
> Okay, that I understand. Thanks for clarification. Sorry about that. Kotlin is still new to me, I more used to other languages. So I try and fail miserably at it sometimes.

your use of kotlin is fine, it is just an issue with the design patterns used in andorid apps and this project

**Pull request closed without merging**
