### PR TITLE
ci: add dependabot

### PR DESCRIPTION
**Pull request by indrastorms**
Need to configure dependabot from repo security settings

### CODE REVIEW

**Comment by IndusAryan** [comment]
This bot is not that great, mend renovate is better plus I update libs manually for cs3 as they are not straight forward like other apps, they fail all the time

**Comment by fire-light42** [comment]
The reason why cs3 does not use dependabot, is because cs3 depends on ***very specific*** versions of packages to work. Such as bumping Jackson above 2.13.1 crashes on Android TV's and FireSticks. Other times updating requires changing a lot of the API, so any automated system creating dummy prs will just make my life harder. 

I will close this PR because this bot will just be unnecessary and annoying. @IndusAryan is a better dependabot.

**Comment by indrastorms** [comment]
It's mainly for track updates if build fails we can try to fix or close the pr the bot will not raise alert until another update.
And if build pass we can manually bump or merge the pr.

**Comment by fire-light42** [comment]
> It's mainly for track updates if build fails we can try to fix or close the pr the bot will not raise alert until another update. And if build pass we can manually bump or merge the pr.

Regressions and crashes are not caught in an automated environment. Each dependency update requires careful testing and consideration. Hence it is less bothersome and time consuming to do large periodic and well tested bumps rather than many small bumps.

**Comment by indrastorms** [comment]
> > It's mainly for track updates if build fails we can try to fix or close the pr the bot will not raise alert until another update. And if build pass we can manually bump or merge the pr.
> 
> Regressions and crashes are not caught in an automated environment. Each dependency update requires careful testing and consideration. Hence it is less bothersome and time consuming to do large periodic and well tested bumps rather than many small bumps.

All hail to @IndusAryan bot! ♥️

**Pull request closed without merging**
