### PR TITLE
Simkl API optimizations

### PR DESCRIPTION
**Pull request by self-similarity**
Using new API features and Caching to reduce requests.

### CODE REVIEW

**Comment by C10udburst** [comment]
CodeFactor jumpscare:

[CodeFactor](https://www.codefactor.io/repository/github/recloudstream/cloudstream) found multiple issues last seen at a1c4ec893a5e0a5cd0d533be08226459feb71921:

#### Parentheses in (searchByIds(realIds)?.firstOrNull()?.also { result -&gt;                 val cacheTime =                     if (result.hasEnded()) SimklCache.CacheTimes.OneMonth.value else SimklCache.CacheTimes.ThirtyMinutes.value                 SimklCache.setKey(idKey, result, Duration.parse(cacheTime))             }) are unnecessary and can be replaced with: searchByIds(realIds)?.firstOrNull()?.also { result -&gt;                 val cacheTime =                     if (result.hasEnded()) SimklCache.CacheTimes.OneMonth.value else SimklCache.CacheTimes.ThirtyMinutes.value                 SimklCache.setKey(idKey, result, Duration.parse(cacheTime))             }
- [ ]  [app\src\main\java\com\lagradost\cloudstream3\syncproviders\providers\SimklApi.kt:798](https://github.com/recloudstream/cloudstream/blob/a1c4ec893a5e0a5cd0d533be08226459feb71921/app/src/main/java/com/lagradost/cloudstream3/syncproviders/providers/SimklApi.kt#L798)

#### Parentheses in (episodes ?: 0) are unnecessary and can be replaced with: episodes ?: 0
- [ ]  [app\src\main\java\com\lagradost\cloudstream3\syncproviders\providers\SimklApi.kt:515](https://github.com/recloudstream/cloudstream/blob/a1c4ec893a5e0a5cd0d533be08226459feb71921/app/src/main/java/com/lagradost/cloudstream3/syncproviders/providers/SimklApi.kt#L515)

#### Parentheses in (oldEpisodes ?: 0) are unnecessary and can be replaced with: oldEpisodes ?: 0
- [ ]  [app\src\main\java\com\lagradost\cloudstream3\syncproviders\providers\SimklApi.kt:416](https://github.com/recloudstream/cloudstream/blob/a1c4ec893a5e0a5cd0d533be08226459feb71921/app/src/main/java/com/lagradost/cloudstream3/syncproviders/providers/SimklApi.kt#L416)
- [ ]  [app\src\main\java\com\lagradost\cloudstream3\syncproviders\providers\SimklApi.kt:413](https://github.com/recloudstream/cloudstream/blob/a1c4ec893a5e0a5cd0d533be08226459feb71921/app/src/main/java/com/lagradost/cloudstream3/syncproviders/providers/SimklApi.kt#L413)

**Comment by LagradOst** [comment]
😢 codefactor when someone write `(1 shl 2) and 2.inv()` instead of `1 shl 2 and 2.inv()`

**Comment by self-similarity** [comment]
Android studio complains back with "_Expression should use clarifying parentheses_" :grimacing:

**Review by C10udburst — APPROVED** [review]
codefactor wrong then

**Pull request merged**
