### PR TITLE
[Refactor] Override domainUrl on select Extractor for changing hostname from extensions

### PR DESCRIPTION
**Pull request by Jacekun**
Ready for merge.

Some providers uses extractors but with different hostname to work.

### CODE REVIEW

**Comment by Blatzar** [comment]
might as well make mainurl overridable then?

**Comment by Jacekun** [comment]
> might as well make mainurl overridable then?

hmm idk. Maybe? DomainUrl is mainly used by XstreamCdn extractor AFAIK.

**Comment by Blatzar** [comment]
> > might as well make mainurl overridable then?
> 
> hmm idk. Maybe? DomainUrl is mainly used by XstreamCdn extractor AFAIK.

I think they do that to sidestep making new classes, tbh we need an entirely new system for that.

**Comment by Jacekun** [comment]
> > > might as well make mainurl overridable then?
> > 
> > 
> > hmm idk. Maybe? DomainUrl is mainly used by XstreamCdn extractor AFAIK.
> 
> I think they do that to sidestep making new classes, tbh we need an entirely new system for that.

Uh kinda. I'm the one who added domainUrl to XtreamCdn. Some extractor sites using XstreamCdn as base only works if the domain for the request is different from the mainUrl. Some uses the site url as domain for XstreamCdn

**Comment by LagradOst** [comment]
> Uh kinda. I'm the one who added domainUrl to XtreamCdn. Some extractor sites using XstreamCdn as base only works if the domain for the request is different from the mainUrl. Some uses the site url as domain for XstreamCdn

I dont get why every api should have it, cant you just use a superclass or interface?

**Comment by Jacekun** [comment]
> > Uh kinda. I'm the one who added domainUrl to XtreamCdn. Some extractor sites using XstreamCdn as base only works if the domain for the request is different from the mainUrl. Some uses the site url as domain for XstreamCdn
> 
> I dont get why every api should have it, cant you just use a superclass or interface?

You're right. It can definitely be accessed thru a superclass of it. I just made it so its easier to access. If you think its not worth the code change, I'll understand.

**Comment by LagradOst** [comment]
Will be closed as stale and not really important

**Pull request closed without merging**
