### PR TITLE
feat(UI): Hide Platform's not related settings

### PR DESCRIPTION
**Pull request by KingLucius**
Hide the below settings

**On Phone**:
- Player -> Android TV.

**On TV**:
- General -> Disable Battery optimization.
- Player -> all "Gesture" section.
- "Accounts and Security" -> "Lock with Biometrics"

### CODE REVIEW

**Comment by fire-light42** [comment]
Looks good 👍

**Comment by Luna712** [comment]
Awesome thanks so much for this. I have wanted this for a long time.

**Comment by KingLucius** [comment]
> Awesome thanks so much for this. I have wanted this for a long time.

I have this idea for a long time also xD

**Comment by IndusAryan** [comment]
can someone explain why try catch was necessary here, its just visibility at the end?

**Comment by KingLucius** [comment]
> can someone explain why try catch was necessary here, its just visibility at the end?

From my side I have followed the same concept of the old code

**Pull request merged**
