### PR TITLE
Move favorites button above bookmarks on TV

### PR DESCRIPTION
**Pull request by Luna712**
I think this looks a bit nicer, but if you don't think it is needed, feel free to close this

### CODE REVIEW

**Comment by Luna712** [comment]
I'm not actually 100% decided on this yet

**Comment by Luna712** [comment]
Might reopen later if I decide this is a good thing, for now, closing though

**Comment by notuser112** [comment]
Maybe move the episode list button above favorite and bookmark button as well. Thanks

**Comment by Luna712** [comment]
> Maybe move the episode list button above favorite and bookmark button as well. Thanks

Yeah that's why I closed this, because it didn't look any better with the episode button there anyway. The order seems off, I just don't know the best way it really should be.

**Pull request closed without merging**
