### PR TITLE
Add favorites

### PR DESCRIPTION
**Pull request by Luna712**
Refs #614

This also hides subscriptions on TV since they can not be used on TV so no reason to show them in library

### CODE REVIEW

**Comment by Luna712** [comment]
This adds favorites to the top bar somewhat based on how subscriptions is done. This way you can add things to specific and favorite them separately, so you can keep better track of shows in the library. Since favorites has a different usage than bookmarks also, it isn't added on the homepage, only to the library. For now, it doesn't work on TV as I couldn't find a good layout implementation for it, so I hid both it and subscriptions in the library since neither can be used on TV, there is no reason for it to be there.

Screenshot_20231012_101418_CloudStream Debug
Screenshot_20231012_101433_CloudStream Debug

**Review by LagradOst — COMMENTED** [review]
code looks fine, however I have not tested it, and no tv support?

**Comment by Luna712** [comment]
> code looks fine, however I have not tested it, and no tv support?

@LagradOst 

No TV support *yet* I might do one on a follow-up, I just could not find a proper place for the UI element on TV layout just yet.

**Comment by Luna712** [comment]
@LagradOst I was able to do TV support now afterall

**Pull request merged**
