### PR TITLE
hotfix: no benene cheat

### PR DESCRIPTION
**Pull request by int3debug**
We don't want cheat benene. We want real benene

Screenshot_2024-04-10-10-06-20-868_dev beefers vendetta_1

### CODE REVIEW

**Comment by IndusAryan** [comment]
no we want bananas to be backed up so that people can continue their streak

**Comment by C10udburst** [comment]
it's a moral obligation to not cheat the benene counter.

**Comment by mizu-048** [comment]
could have atleast informed me, i would have put a better profile picture

**Comment by mizu-048** [comment]
could have atleast informed me, i would have put a better profile picture

**Comment by mizu-048** [comment]
could have atleast informed me, i would have put a better profile picture

**Comment by watashinosoulsociety** [comment]
> could have atleast informed me, i would have put a better profile picture

Where have been so many days wtf

**Comment by mizu-048** [comment]
who you

**Comment by watashinosoulsociety** [comment]
> who you

Rydel

**Pull request closed without merging**
