### PR TITLE
Next Airing episode support in Trakt meta provider

### PR DESCRIPTION
**Pull request by KingLucius**

### CODE REVIEW

**Comment by fire-light42** [comment]
`file:///home/runner/work/cloudstream/cloudstream/app/src/main/java/com/lagradost/cloudstream3/metaproviders/TraktProvider.kt:217:37 Cannot find a parameter with this name: season`

https://github.com/recloudstream/cloudstream/blob/d3828eeafed0fd4fbeb32c4d37dee2126296b564/app/src/main/java/com/lagradost/cloudstream3/MainAPI.kt#L1452

**Comment by fire-light42** [comment]
I assume you mean #1071 to be merged first

**Comment by KingLucius** [comment]
> I assume you mean #1071 to be merged first

Exactly 🙏

**Comment by KingLucius** [comment]
As #1071 is merged, this can be merged now safely

**Comment by fire-light42** [comment]
Reran the build but never merged it.

**Review by fire-light42 — APPROVED** [review]

**Pull request merged**
