### PR TITLE
feat: make cloudstream fast boi, ksp migration

### PR DESCRIPTION
**Pull request by IndusAryan**
https://developer.android.com/build/migrate-to-ksp

recommended

### CODE REVIEW

**Comment by LagradOst** [comment]
bro, you cant simply remove glideapp???? it has overrides we use

**Comment by Blatzar** [comment]
GlideApp gets generated from [this](https://github.com/recloudstream/cloudstream/blob/master/app/src/main/java/com/lagradost/cloudstream3/utils/GlideApp.kt#L23-L55), which features critical functionality like DOH and cache size :+1: 
Just changing it to the default glide removes this. Although it is very easy to miss this code since it is not directly referenced anywhere.

**Comment by Blatzar** [comment]
Wow! That actually works
I am seldom surprised using kotlin, but damn
I checked that requests were sent correctly using a custom interceptor:

```kt
        val client =
            Requests().apply {
                defaultHeaders = mapOf("user-agent" to USER_AGENT)
            }.initClient(context)
                .newBuilder()
                .addInterceptor {
                    val request = it.request()
                    println("Request: ${request.url}")
                    it.proceed(request)
                }
                .addInterceptor(DdosGuardKiller(false))
                .build()
```
And it did work :pray:

**Comment by Blatzar** [comment]
I am just not used to annotation magic, other languages can probably do this too :shrug: 
I just thought com.bumptech.glide.Glide would not use our GlideApp, it looks like any other innocent import.
Previously the class was generated and that was more intuitive, but this is better since they wont be undefined before building :+1: 

Good job :pray:

**Comment by fire-light42** [comment]
@LagradOst Did you test this pr?

**Comment by fire-light42** [comment]
It build for me at least

**Pull request merged**
