### PR TITLE
Delete Focus frame from empty Downloads list & Search TV Layout

### PR DESCRIPTION
**Pull request by KingLucius**

### CODE REVIEW

**Comment by LagradOst** [comment]
🤨 if you want to actually remove it from the chips then you need to add it to the style

**Comment by KingLucius** [comment]
Ok will update the PR

**Comment by LagradOst** [comment]
I am actually on the fence about removing the white square entirely as too many ppl complain

**Comment by KingLucius** [comment]
So there is no meaning for this PR, i think we can close it then.

**Comment by KingLucius** [comment]
Removed the white square frame with tag via style & added rounded stroke as on TV it's hard to recognize the focused chip

**Pull request merged**
