### PR TITLE
add voting system

### PR DESCRIPTION
**Pull request by C10udburst**

### CODE REVIEW

**Review by Blatzar — APPROVED** [review]
I don't think I would change a single line, it looks great!

**Comment by LagradOst** [comment]
Everything looks fine, however I would rename Votes: 1 to rated or likes. Also sorting by votes, however that is really not needed

**Comment by LagradOst** [comment]
Also it defaults to 10K if you dont have any internet

**Comment by C10udburst** [comment]
> Everything looks fine, however I would rename Votes: 1 to rated or likes. Also sorting by votes, however that is really not needed

what about karma :trollface:

**Comment by Blatzar** [comment]
> what about karma :trollface:

:skull:

**Comment by Blatzar** [comment]
Bananas would unironically work :flushed:

**Comment by C10udburst** [comment]
> Bananas would unironically work 😳

all right :shipit:

**Pull request merged**
