### PR TITLE
Updated italian translation

### PR DESCRIPTION
**Pull request by Yoddikko**

### CODE REVIEW

**Comment by Yoddikko** [comment]
Why the checks fails, I just changed the xml

**Comment by Blatzar** [comment]
You need to escape some characters in xml, e.g '
Which means you should do \\'

I can fix the errors

**Comment by Yoddikko** [comment]
Oh okay, thank you

**Comment by Blatzar** [comment]
@Yoddikko Ready for merge?

**Comment by Yoddikko** [comment]
> @Yoddikko Ready for merge?

Do I need to do something?

**Pull request merged**
