### PR TITLE
Use user setting for seeking on Android TV

### PR DESCRIPTION
**Pull request by TerHano**

### CODE REVIEW

**Comment by LagradOst** [comment]
@doteq

**Comment by bachig26** [comment]
@TerHano I don't understand much (on coding), but looking at the changes. it looks same.
It looks like both left and right key executes the forward seek.

**Comment by TerHano** [comment]
> @TerHano I don't understand much (on coding), but looking at the changes. it looks same.
> It looks like both left and right key executes the forward seek.

Sorry about that, I had done some edits prior to checking in and it looks like the minus was deleted. Should be fixed now.

**Comment by doteq** [comment]
When I was designing TV UI I wanted to have two ways of seeking.
 - If you couldn't hear something you can just rewind 10 seconds by clicking left button without interface opened
 - If you want to find some part in video you can seek by 30 seconds when interface is opened
 I feel that my design is very intuitive because it gives you more control when seeking. You could add second "TV seeking time" setting, so users can tweak that and use it here, but using only one value is a bad idea.

**Comment by TerHano** [comment]
I agree that having two settings would be nice. I made the change and added the settings, let me know if it's what you had in mind.

**Comment by doteq** [comment]
I would remove semicolons, because you don't need them in kotlin and it looks weird when only your lines have them, but overall looks good to me, great work :)

**Comment by LagradOst** [comment]
LGTM, ready to merge?

**Pull request merged**
