### PR TITLE
Simplified Chinese Correction and Update

### PR DESCRIPTION
**Pull request by Sdarfeesh**

### CODE REVIEW

**Comment by Sdarfeesh** [comment]
Btw, how should i translate [This](https://github.com/recloudstream/cloudstream/blob/master/app/src/main/res/values-zh/strings.xml#L234)?
if i change the format, the season button will be missing

**Comment by Blatzar** [comment]
You pretty much need to keep the format afaik :thinking: 
%s
It "season" from the xml youre translating
%d
the number of the season
%s
optional additional name set by extensions, e.g "Premium" iirc

**Comment by Blatzar** [comment]
Ready for merge?

**Comment by Sdarfeesh** [comment]
> Ready for merge?

Sure

**Review by C10udburst — APPROVED** [review]

**Pull request merged**
